# 系统配置示例文件
# 复制此文件为config.yaml并根据实际环境修改配置
# 或者使用环境变量覆盖这些配置项 (例如: APP_SERVICES_GPU_URL)

services:
  gpu:
    # GPU服务地址，请替换为实际地址
    url: "http://{GPU_HOST}:{GPU_PORT}/v1/completions"
    metrics_url: "http://{GPU_HOST}:{GPU_PORT}/metrics"
  cpu:
    # CPU服务地址，请替换为实际地址
    url: "http://{CPU_HOST}:{CPU_PORT}/v1/completions"
    metrics_url: "http://{CPU_HOST}:{CPU_PORT}/metrics"

models:
  # 指定使用的模型
  default: "{MODEL_NAME}"
  params:
    # 生成的最大token数量
    max_tokens: 200
    # 生成随机性参数 (0.0-1.0)
    temperature: 0.7
    # 性能测试使用的提示语
    test_prompt: "这是一个标准测试语句，用于测试模型的性能。"
    # 性能测试生成的token数量
    test_tokens: 30

system:
  # 请求队列大小
  max_queue_size: 200
  # 请求超时时间(秒)
  request_timeout: 600